export const filas = [
    {
      producto: "manzana",
      cantidad: 2,
      precio: 3.4,
      tienda: "Mercadona",
      notas: "Comprar 3",
      comprado: true,
      imagen: "https://pngimg.com/uploads/apple/apple_PNG12509.png",
    },
    {
      producto: "plátano",
      cantidad: 5,
      precio: 2.1,
      tienda: "Lidl",
      notas: "Comprar maduros",
      comprado: false,
      imagen: "https://cdn.pixabay.com/photo/2016/02/23/17/29/banana-1218133_1280.png",
    },
    {
      producto: "leche",
      cantidad: 1,
      precio: 1.2,
      tienda: "Carrefour",
      notas: "Desnatada",
      comprado: true,
      imagen: "https://th.bing.com/th/id/OIP.wLG_dTb6RCJqn-YaANh_KwHaIT?rs=1&pid=ImgDetMain",
    },
    {
      producto: "pan",
      cantidad: 3,
      precio: 1.5,
      tienda: "Día",
      notas: "Integral",
      comprado: false,
      imagen: "https://th.bing.com/th/id/R.3e6ecd9afbc8c081722c114c5ffa937b?rik=j2mbHbtVuO1rog&pid=ImgRaw&r=0",
    },
    {
      producto: "queso",
      cantidad: 1,
      precio: 4.5,
      tienda: "Aldi",
      notas: "Cheddar",
      comprado: false,
      imagen: "https://pngimg.com/uploads/cheese/cheese_PNG25282.png",
    },
  ];
  